### ISSUE TITLE
Praca domowa

### ISSUE THREAD

**Issue by Madziorex** [StanleyN0vak/AISD-Poprawkowa#1]
dodawanie tablic odwrotnie
{1,2,3}
jednostki, dziesiątki, setki(czyli odwrotnie)
pisemnie umiemy dodawać

**Comment by StanleyN0vak** [comment]
[https://github.com/StanleyN0vak/AISD-Poprawkowa/tree/main/Dodawanie_Pod_Kreska_PD/Tabela_Dod_pod_kreska](url)
Zrobione, może i nie wygląda za to nawet działa
