### ISSUE TITLE
Prdom2

### ISSUE THREAD

**Issue by Madziorex** [StanleyN0vak/AISD-Poprawkowa#2]
selekcją?
sortowanie przez wybieranie

**Comment by StanleyN0vak** [comment]
[https://github.com/StanleyN0vak/AISD-Poprawkowa/tree/main/Select_sort](url)
Zrobione, wzorowane na sortowaniu bąbelkowym.
Trzeba było wziąć indeks jednej wartości i przeszukać całą tabelę w poszukiwaniu wartości mniejszej, jeśli taka jest to zamieniamy wartości w danych indeksach. Powtarzamy do puki już nie było żadnej zmiany w tabeli.
